# Builds the logos-wallet-module library
{ pkgs, common, src, goWalletSdk, logosSdk, goWalletLib }:

pkgs.stdenv.mkDerivation {
  pname = "${common.pname}-lib";
  version = common.version;
  
  inherit src;
  inherit (common) buildInputs cmakeFlags meta env;
  
  # Add logosSdk to nativeBuildInputs for logos-cpp-generator
  nativeBuildInputs = common.nativeBuildInputs ++ [ logosSdk ];
  
  preConfigure = ''
    runHook prePreConfigure
    
    # Create generated_code directory for generated files
    mkdir -p ./generated_code
    
    # Use the prebuilt Go wallet library from goWalletLib
    echo "Using prebuilt Go wallet library from goWalletLib"
    mkdir -p lib
    cp -L ${goWalletLib}/lib/libgowalletsdk.* lib/ || {
      echo "Error: Could not copy prebuilt Go wallet library"
      echo "Contents of ${goWalletLib}/lib/:"
      ls -la ${goWalletLib}/lib/ || echo "Directory not found"
      exit 1
    }
    echo "Go wallet library copied to lib/"
    echo "Contents of lib/:"
    ls -la lib/
    
    # Run logos-cpp-generator with metadata.json and --general-only flag
    echo "Running logos-cpp-generator..."
    logos-cpp-generator --metadata ${src}/metadata.json --general-only --output-dir ./generated_code
    
    # Check what was generated by logos-cpp-generator
    echo "Checking generated files in generated_code:"
    ls -la ./generated_code/
    
    # Create include directory and move generated files there if they exist
    if [ -f "./generated_code/core_manager_api.h" ] || [ -f "./generated_code/logos_sdk.h" ]; then
      echo "Creating include directory and moving generated files..."
      mkdir -p ./generated_code/include
      # Move generated header files to include directory
      for file in ./generated_code/*.h; do
        if [ -f "$file" ]; then
          mv "$file" ./generated_code/include/
        fi
      done
      # Also copy generated .cpp files to include directory
      for file in ./generated_code/*.cpp; do
        if [ -f "$file" ]; then
          cp "$file" ./generated_code/include/
        fi
      done
      echo "Generated include directory:"
      ls -la ./generated_code/include/
    else
      echo "Warning: No header files generated by logos-cpp-generator"
    fi
    
    runHook postPreConfigure
  '';
  
  installPhase = ''
    runHook preInstall
    
    mkdir -p $out/lib
    # Find and copy the built library file from the modules directory
    if [ -f modules/wallet_module_plugin.dylib ]; then
      cp modules/wallet_module_plugin.dylib $out/lib/
    elif [ -f modules/wallet_module_plugin.so ]; then
      cp modules/wallet_module_plugin.so $out/lib/
    else
      echo "Error: No library file found"
      exit 1
    fi
    
    # Copy the wallet library if it exists (check both lib/ and modules/ directories)
    if [ -f lib/libgowalletsdk.dylib ]; then
      cp lib/libgowalletsdk.dylib $out/lib/
      echo "Copied libgowalletsdk.dylib from lib/ to $out/lib/"
    elif [ -f modules/libgowalletsdk.dylib ]; then
      cp modules/libgowalletsdk.dylib $out/lib/
      echo "Copied libgowalletsdk.dylib from modules/ to $out/lib/"
    elif [ -f lib/libgowalletsdk.so ]; then
      cp lib/libgowalletsdk.so $out/lib/
      echo "Copied libgowalletsdk.so from lib/ to $out/lib/"
    elif [ -f modules/libgowalletsdk.so ]; then
      cp modules/libgowalletsdk.so $out/lib/
      echo "Copied libgowalletsdk.so from modules/ to $out/lib/"
    else
      echo "Warning: No wallet library found in lib/ or modules/"
      echo "Contents of lib/:"
      ls -la lib/ 2>/dev/null || echo "lib/ directory does not exist"
      echo "Contents of modules/:"
      ls -la modules/ 2>/dev/null || echo "modules/ directory does not exist"
    fi
    
    # Also install the generated include files
    if [ -d "./generated_code/include" ]; then
      mkdir -p $out/include
      cp -r ./generated_code/include/* $out/include/
      echo "Installed generated include files:"
      ls -la $out/include/
    fi
    
    runHook postInstall
  '';
}
