# Builds the logos-wallet-module library
{ pkgs, common, src, logosSdk, goWalletSdkLib }:

pkgs.stdenv.mkDerivation {
  pname = "${common.pname}-lib";
  version = common.version;
  
  inherit src;
  inherit (common) buildInputs cmakeFlags meta env;
  
  nativeBuildInputs = common.nativeBuildInputs ++ [ logosSdk ];
  
  preConfigure = ''
    runHook prePreConfigure
    
    mkdir -p ./generated_code
    
    # Use the pre-built Go library
    mkdir -p lib
    cp ${goWalletSdkLib}/lib/libgowalletsdk.* lib/
    echo "Wallet C library copied into lib/"
    ls -la lib/
    
    # Run logos-cpp-generator with metadata.json and --general-only flag
    echo "Running logos-cpp-generator..."
    logos-cpp-generator --metadata ${src}/metadata.json --general-only --output-dir ./generated_code
    
    # Check what was generated by logos-cpp-generator
    echo "Checking generated files in generated_code:"
    ls -la ./generated_code/
    
    # Create include directory and move generated files there if they exist
    if [ -f "./generated_code/core_manager_api.h" ] || [ -f "./generated_code/logos_sdk.h" ]; then
      echo "Creating include directory and moving generated files..."
      mkdir -p ./generated_code/include
      for file in ./generated_code/*.h; do
        if [ -f "$file" ]; then
          mv "$file" ./generated_code/include/
        fi
      done
      for file in ./generated_code/*.cpp; do
        if [ -f "$file" ]; then
          cp "$file" ./generated_code/include/
        fi
      done
      echo "Generated include directory:"
      ls -la ./generated_code/include/
    else
      echo "Warning: No header files generated by logos-cpp-generator"
    fi
    
    runHook postPreConfigure
  '';
  
  installPhase = ''
    runHook preInstall
    
    mkdir -p $out/lib
    if [ -f modules/wallet_module_plugin.dylib ]; then
      cp modules/wallet_module_plugin.dylib $out/lib/
    elif [ -f modules/wallet_module_plugin.so ]; then
      cp modules/wallet_module_plugin.so $out/lib/
    else
      echo "Error: No library file found"
      exit 1
    fi
    
    if [ -d "./generated_code/include" ]; then
      mkdir -p $out/include
      cp -r ./generated_code/include/* $out/include/
      echo "Installed generated include files:"
      ls -la $out/include/
    fi
    
    runHook postInstall
  '';
}
