// Stub header for unit tests — declares the Go Wallet SDK C API used by wallet_module_impl.
// The real header is generated by CGo during the Go build and placed at lib/.

#ifndef LIBGOWALLETSDK_H
#define LIBGOWALLETSDK_H

#include <stdint.h>

typedef unsigned long long GoWSKHandle;

void GoWSK_FreeCString(char* str);

GoWSKHandle GoWSK_ethclient_NewClient(char* rpcUrl, char** error);
void GoWSK_ethclient_CloseClient(GoWSKHandle handle);
char* GoWSK_ethclient_ChainID(GoWSKHandle handle, char** error);
char* GoWSK_ethclient_GetBalance(GoWSKHandle handle, char* address, char** error);
char* GoWSK_ethclient_RPCCall(GoWSKHandle handle, char* method, char* paramsJSON, char** error);

char* GoWSK_transaction_JSONToRLP(char* txJSON, char** error);
char* GoWSK_transaction_RLPToJSON(char* rlpHex, char** error);
char* GoWSK_transaction_GetHash(char* txJSON, char** error);

char* GoWSK_txgenerator_TransferETH(char* paramsJSON, char** error);
char* GoWSK_txgenerator_TransferERC20(char* paramsJSON, char** error);
char* GoWSK_txgenerator_ApproveERC20(char* paramsJSON, char** error);
char* GoWSK_txgenerator_TransferFromERC721(char* paramsJSON, char** error);
char* GoWSK_txgenerator_SafeTransferFromERC721(char* paramsJSON, char** error);
char* GoWSK_txgenerator_ApproveERC721(char* paramsJSON, char** error);
char* GoWSK_txgenerator_SetApprovalForAllERC721(char* paramsJSON, char** error);
char* GoWSK_txgenerator_TransferERC1155(char* paramsJSON, char** error);
char* GoWSK_txgenerator_BatchTransferERC1155(char* paramsJSON, char** error);
char* GoWSK_txgenerator_SetApprovalForAllERC1155(char* paramsJSON, char** error);

#endif
